import React from 'react'

export const metadata = {
  title: "Services page",
  description: "Generated by create next app",
};

const Services = () => {
  return (
    <div>Services</div>
  )
}

export default Services